sonar.projectKey=RvbyY_lovable-project-6590fb53-f408-47c3-b75b-a0935ca01755-2026-03-05
sonar.organization=rvbyy


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=lovable-project-6590fb53-f408-47c3-b75b-a0935ca01755-2026-03-05
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8